# Generated by Django 3.2.9 on 2021-11-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_alter_videos_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='demo',
            new_name='isDemo',
        ),
    ]
