# Generated by Django 3.2.9 on 2021-11-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_rename_demo_videos_isdemo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='isDemo',
            new_name='demo',
        ),
    ]
