# Generated by Django 3.2.9 on 2021-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_rename_isdemo_videos_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='familyName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='familyName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
