# Generated by Django 3.2.9 on 2021-12-11 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('price', models.FloatField(default=0)),
                ('subTittel', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('datepublished', models.DateTimeField(null=True)),
                ('stutus', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('course_pic', models.ImageField(blank=True, null=True, upload_to='courses/coverPictures/')),
                ('duration', models.DurationField(max_length=100, null=True)),
                ('fileZip', models.FileField(blank=True, null=True, upload_to='courses/zipFile/')),
                ('dlNumber', models.IntegerField(default=0)),
                ('video', models.FileField(blank=True, null=True, upload_to='courses/video/%y')),
                ('category', models.ManyToManyField(related_name='category', to='mainSite.Category')),
            ],
            options={
                'ordering': ['-dlNumber'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='teacher/profile/picture')),
                ('fildOfStudy', models.CharField(max_length=60, null=True)),
                ('university', models.CharField(max_length=60, null=True)),
                ('lastEducation', models.CharField(choices=[('b', 'Bachelor'), ('bs', 'Bachelor Student'), ('m', 'Master'), ('ms', 'Master Student'), ('p', 'PHD'), ('ps', 'PHD Student')], default='bs', max_length=2)),
                ('documents', models.FileField(blank=True, null=True, upload_to='teacher/documents/')),
                ('companiName1', models.CharField(max_length=50, null=True)),
                ('jobSituation1', models.CharField(max_length=50, null=True)),
                ('companiName2', models.CharField(max_length=50, null=True)),
                ('jobSituation2', models.CharField(max_length=50, null=True)),
                ('courseTitle1', models.CharField(max_length=50, null=True)),
                ('courseTime1', models.CharField(max_length=50, null=True)),
                ('courseTitle2', models.CharField(max_length=50, null=True)),
                ('courseTime2', models.CharField(max_length=50, null=True)),
                ('exteraInfo', models.CharField(max_length=200, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('wallet', models.FloatField(default=0)),
                ('course', models.ManyToManyField(related_name='teacher', to='mainSite.Course')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('contry', models.CharField(blank=True, choices=[('ir', 'Iran'), ('us', 'Usa'), ('ca', 'Canada'), ('ch', 'China'), ('in', 'India')], default='ir', max_length=2)),
                ('adress', models.CharField(max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('course', models.ManyToManyField(related_name='my', to='mainSite.Course')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
