# Generated by Django 3.2.9 on 2021-12-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.ManyToManyField(related_name='course', to='mainSite.Course'),
        ),
    ]
