# Generated by Django 3.2.9 on 2021-12-05 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='course', to='mainSite.Category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.ManyToManyField(related_name='customer', to='mainSite.Course'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='teacher', to='mainSite.Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
