# Generated by Django 3.2.9 on 2021-12-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_auto_20211205_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='category', to='mainSite.Category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.ManyToManyField(related_name='my', to='mainSite.Course'),
        ),
    ]
