# Generated by Django 3.2.9 on 2021-12-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_auto_20211207_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='documents',
        ),
        migrations.AddField(
            model_name='teacher',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='teacher/documents/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/profile/picture'),
        ),
    ]
