# Generated by Django 3.2.9 on 2021-12-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_auto_20211212_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
