# Generated by Django 3.2.9 on 2021-12-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_auto_20211207_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
