# Generated by Django 3.2.9 on 2021-12-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_delete_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-price']},
        ),
    ]
