# Generated by Django 3.2.9 on 2022-01-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_auto_20220104_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
