# Generated by Django 3.2.9 on 2022-01-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_transaction_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tacher',
            new_name='teacher',
        ),
    ]
