# Generated by Django 3.2.9 on 2022-01-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0007_rename_tacher_transaction_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
