# Generated by Django 3.2.9 on 2021-12-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0007_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-dlNumber']},
        ),
    ]
