# Generated by Django 3.2.9 on 2021-12-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0008_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datepublished',
            field=models.DateTimeField(null=True),
        ),
    ]
