# Generated by Django 3.2.9 on 2021-12-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0009_alter_course_datepublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover',
        ),
        migrations.AddField(
            model_name='teacher',
            name='companiName1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='companiName2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courseTime1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courseTime2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courseTitle1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='jobSituation1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_pic',
            field=models.ImageField(blank=True, null=True, upload_to='courses/coverPictures/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fileZip',
            field=models.FileField(blank=True, null=True, upload_to='courses/zipFile/'),
        ),
    ]
