# Generated by Django 3.2.9 on 2021-12-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0010_auto_20211211_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courseTitle2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='jobSituation2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
