# Generated by Django 3.2.9 on 2021-12-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0011_auto_20211211_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='exteraInfo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
