# Generated by Django 3.2.9 on 2021-12-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0012_teacher_exterainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
