# Generated by Django 3.2.9 on 2021-12-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0014_alter_teacher_companiname1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='companiName1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
